"""initial schema

Revision ID: aa9f06b7647b
Revises: 
Create Date: 2026-10-03 11:23:07.878038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9f06b7647b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.String(length=24), nullable=False),
    sa.Column('revoked_at', sa.String(length=24), nullable=True),
    sa.Column('last_used_at', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('time_local', sa.String(length=5), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=False),
    sa.Column('expires_after_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=24), nullable=False),
    sa.Column('updated_at', sa.String(length=24), nullable=False),
    sa.Column('deleted_at', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_table('checkin_questions',
    sa.Column('checkin_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['checkin_id'], ['checkins.id'], ),
    sa.PrimaryKeyConstraint('checkin_id', 'question_id')
    )
    op.create_table('responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_version', sa.Integer(), nullable=False),
    sa.Column('checkin_id', sa.Integer(), nullable=True),
    sa.Column('instance_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('value', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('scheduled_for', sa.String(length=24), nullable=True),
    sa.Column('answered_at', sa.String(length=24), nullable=False),
    sa.Column('received_at', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['checkin_id'], ['checkins.id'], ),
    sa.ForeignKeyConstraint(['question_id', 'question_version'], ['questions.id', 'questions.version'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.create_index('ix_responses_answered_at', ['answered_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index('ix_responses_answered_at')

    op.drop_table('responses')
    op.drop_table('checkin_questions')
    op.drop_table('questions')
    op.drop_table('meta')
    op.drop_table('checkins')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
